name: Build Pyinstaller windows only

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - develop2

jobs:
  build:
    name: Build windows only (${{ matrix.python-version }}
    runs-on: windows-latest  # Only run on Windows
    strategy:
      fail-fast: false  # Don't cancel other jobs if one fails
      matrix:
        #os: [ubuntu-latest, windows-latest]
        python-version: [ '3.11']
        solver: ["classic"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          activate-environment: QA
          channels: swisstopo,conda-forge  # defaults is included
          channel-priority: flexible
          environment-file: windows-3.11-environment.yaml
          
          
      - name: Install packages in PowerShell Core
        shell: pwsh
        run: |
          conda install conda-build anaconda-client conda-verify  versioneer setuptools setuptools_scm jinja2 libffi pyyaml click geopandas gdal fiona pandas loguru shapely babel jsonschema openpyxl ruamel.yaml coverage -y
          conda list
          echo $env:CONDA_PREFIX
          conda env export 
          
      - name: Build pyinstaller package
        shell: bash -el {0}
        run: |
          conda install pyinstaller -y
          pip install -e ".[gui]"
          pyinstaller gui/geocover-qa.spec --distpath dist/gui --workpath build/gui
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: geocover-qa-gui-${{ matrix.python-version }}
          path: |
            dist/gui/*
          
     
