name: Build Conda Environnement

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - develop2

jobs:
  build:
    name: Build windows only (${{ matrix.python-version }}
    runs-on: windows-latest  # Only run on Windows
    strategy:
      fail-fast: false  # Don't cancel other jobs if one fails
      matrix:
        #os: [ubuntu-latest, windows-latest]
        python-version: [ '3.11']
        solver: ["classic"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          activate-environment: QA
          channels: swisstopo,conda-forge  # defaults is included
          channel-priority: flexible
          
          
      - name: Conda in PowerShell
        shell: powershell
        run: |
          conda info
          conda list
      - name: Install packages in PowerShell Core
        shell: pwsh
        run: |
          conda install conda-build anaconda-client conda-verify  versioneer setuptools setuptools_scm 
          conda install jinja2 libffi pyyaml click geopandas pandas loguru shapely >= 2.0.0 babel jsonschema openpyxl ruamel.yaml coverage unittests
          conda list
          echo $env:CONDA_PREFIX
          
      - name: Build Conda Package
        shell: pwsh
        run: |
          conda build . --output-folder dist/conda --python ${{ matrix.python-version }}
      - name: Build pyinstaller package
        shell: bash -el {0}
        run: |
          pip install pyinstaller
          pip install -e ".[gui]"
          pyinstaller gui/geocover-qa.spec --distpath dist/gui --workpath build/gui
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: conda-packages-py${{ matrix.python-version }}
          path: |
            dist/conda/*
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: geocover-qa-gui-${{ matrix.python-version }}
          path: |
            dist/gui/*
            




